### ISSUE TITLE
Find nth Fibonacci number using dynamic programming

### ISSUE THREAD

**Issue by harshjais369** [CodeXstalker/DSA-Directory#7]
Hello @ShivanshKumar200496 sir, could you assign me this issue. I want to work on this issue under hacktoberfest.

As a beginner in open-source projects community, I want learn and grow within this, so I thought implementing the Fibonacci series using dynamic programming will be a good starting point for me. Let me know if this is a something you would be interested in, and as well as aligns with the project's end goals.

Any further guidance on this, is much appreciated!..

**Comment by ShivanshKumar4265** [comment]
This isuue has been assigned to @harshjais369

**Comment by ShivanshKumar4265** [comment]
@harshjais369 For contribution, please create new branch with name "yourname_gmail"

**Comment by harshjais369** [comment]
@CodeXstalker Sure sir, will do the needful accordingly. Kindly lable this issue under hacktoberfest.

**Comment by ShivanshKumar4265** [comment]
@harshjais369 try to solve this by  13 oct 2023,
Othrerwise will close this issue

**Comment by harshjais369** [comment]
@CodeXstalker hi, I've made the pull request. Please take your time to review my code, and let me know if there are any additional changes or feedback you might have.

**Comment by harshjais369** [comment]
Sorry for the delay, actually I could have done it before by yesterday, but couldn't due to some network issues..
